version: '3'

services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    links:
      - mariadb
    networks:
      - default
    ports:
      - 8080:80

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: listatelefonica
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - mariadb-data:/var/lib/mysql
    networks:
      - default
    ports:
      - 3306:3306
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8090:80
    environment:
      PMA_HOST: mariadb 
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: listatelefonica
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha
    links:
      - mariadb
    networks:
      - default



volumes:
  mariadb-data: